/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;


import DAO.produtoDAO;
import Entidades.Produto;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miriam
 */
public class NewJFrameProduto extends javax.swing.JFrame {
private int id;
    /**
     * Creates new form NewJFrameProduto
     */
    public NewJFrameProduto() {
        
        initComponents();
        carregaProduto();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1descricao = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jTextField3preco = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jTextField2quantidade = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1inserir = new javax.swing.JButton();
        jButton2cancelar = new javax.swing.JButton();
        jButton3salvar = new javax.swing.JButton();
        jButton4atualizar = new javax.swing.JButton();
        jButton5excluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Produto"));

        jLabel1.setText("Descrição:");

        jTextField1descricao.setEnabled(false);

        jLabel3.setText("Preço:");

        jTextField3preco.setEnabled(false);

        jLabel2.setText("Quantidade:");

        jTextField2quantidade.setEnabled(false);
        jTextField2quantidade.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2quantidadeActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel3)
                        .addComponent(jLabel2))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel1)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField3preco, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1descricao)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextField2quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, 54, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap())))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField1descricao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jTextField3preco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jTextField2quantidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jButton1inserir.setText("Inserir");
        jButton1inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1inserirActionPerformed(evt);
            }
        });

        jButton2cancelar.setText("Cancelar");
        jButton2cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2cancelarActionPerformed(evt);
            }
        });

        jButton3salvar.setText("Salvar");
        jButton3salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3salvarActionPerformed(evt);
            }
        });

        jButton4atualizar.setText("Atualizar");
        jButton4atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4atualizarActionPerformed(evt);
            }
        });

        jButton5excluir.setText("Excluir");
        jButton5excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5excluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jButton1inserir)
                .addGap(18, 18, 18)
                .addComponent(jButton2cancelar)
                .addGap(25, 25, 25)
                .addComponent(jButton3salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton4atualizar)
                .addGap(27, 27, 27)
                .addComponent(jButton5excluir)
                .addGap(23, 23, 23))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1inserir)
                    .addComponent(jButton2cancelar)
                    .addComponent(jButton3salvar)
                    .addComponent(jButton4atualizar)
                    .addComponent(jButton5excluir))
                .addContainerGap(29, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Produtos"));

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable2MouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTable2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 181, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1inserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1inserirActionPerformed
        // TODO add your handling code here:
       
        jTextField1descricao.setEnabled(true);
       jTextField2quantidade.setEnabled(true);
        jTextField3preco.setEnabled(true);
        
        
    }//GEN-LAST:event_jButton1inserirActionPerformed

    private void jButton2cancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2cancelarActionPerformed
        // TODO add your handling code here:
        
         jTextField1descricao.setText("");
       jTextField2quantidade.setText("");
        jTextField3preco.setText("");
       
        
         jTextField1descricao.setEnabled(false);
       jTextField2quantidade.setEnabled(false);
        jTextField3preco.setEnabled(false);
       
    }//GEN-LAST:event_jButton2cancelarActionPerformed

    private void jButton3salvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3salvarActionPerformed
        // TODO add your handling code here:
        if(jTextField1descricao.isEnabled()){
           Produto usu = new Produto();
           
           
            if(jTextField1descricao.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o produto do cliente!");
                return;
            }
            else{
                usu.setDescricao(jTextField1descricao.getText());
            }
            
             if(jTextField3preco.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o preço do produto!");
                return;
            }
            else{
                usu.setPreco(Double.parseDouble(jTextField3preco.getText()));
            }
             if(jTextField2quantidade.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira a quantidade do produto!");
                return;
            }
            else{
                usu.setQuant(Integer.parseInt(jTextField2quantidade.getText()));
            }
             
             
             produtoDAO.cadastrar(usu);
             carregaProduto();
            jButton2cancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton3salvarActionPerformed

    private void jButton4atualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4atualizarActionPerformed
        // TODO add your handling code here:
         if(jTable2.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela!");
        }
        else if(JOptionPane.showConfirmDialog(this,"Tem certeza que deseja alterar o produto "+ jTable2.getModel().getValueAt(jTable2.getSelectedRow(),1)+"!")
                ==JOptionPane.OK_OPTION){
            Produto usu = new Produto();
            
            usu.setId(id);
             
            if(jTextField1descricao.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira a descrição!");
                return;
            
        }else{
            usu.setDescricao(jTextField1descricao.getText());
        }
           
             if(jTextField3preco.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o preço!");
                return;
            }
            else{
                usu.setPreco(Double.parseDouble(jTextField3preco.getText()));
            }
             if(jTextField2quantidade.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira a quantidade do produto!");
                return;
            }
            else{
                usu.setQuant(Integer.parseInt(jTextField2quantidade.getText()));
            }
             
             
             produtoDAO.alterar(usu);
             carregaProduto();
             jButton2cancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton4atualizarActionPerformed

    private void jButton5excluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5excluirActionPerformed
        // TODO add your handling code here:
         if(jTable2.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Slelecione uma linha da tabela!");
            
        }
        else if(JOptionPane.showConfirmDialog(this,"Tem certeza que deseja excluir este produto?")==JOptionPane.YES_OPTION){
            id=(int)jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 0);
            produtoDAO.excluir(id);
             carregaProduto();
             jButton2cancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton5excluirActionPerformed

    private void jTable2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable2MouseClicked
        // TODO add your handling code here:
        jButton1inserirActionPerformed(null);
       id= (int) jTable2.getModel().getValueAt(jTable2.getSelectedRow(),0);
       jTextField1descricao.setText("" +jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 1));
          jTextField3preco.setText(""+jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 2));
           jTextField2quantidade.setText("" +jTable2.getModel().getValueAt(jTable2.getSelectedRow(), 3));
    }//GEN-LAST:event_jTable2MouseClicked

    private void jTextField2quantidadeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2quantidadeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2quantidadeActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameProduto.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameProduto().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1inserir;
    private javax.swing.JButton jButton2cancelar;
    private javax.swing.JButton jButton3salvar;
    private javax.swing.JButton jButton4atualizar;
    private javax.swing.JButton jButton5excluir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTable1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTextField jTextField1descricao;
    private javax.swing.JTextField jTextField2quantidade;
    private javax.swing.JTextField jTextField3preco;
    // End of variables declaration//GEN-END:variables
public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}
    private void carregaProduto() {
         try{
        jTable2.setModel(buildTableModel(produtoDAO.consulta()));
    }   catch (SQLException ex) {
            Logger.getLogger(NewJFrameProduto.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    
}
