/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;

import DAO.clienteDAO;
import Entidades.Cliente;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miriam
 */
public class NewJFrameCliente extends javax.swing.JFrame {
  private int id;
    /**
     * Creates new form NewJFrameCliente
     */
    public NewJFrameCliente() {
        initComponents();
        carregaCliente();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldendereco = new javax.swing.JTextField();
        jTextFieldemail = new javax.swing.JTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1Inserir = new javax.swing.JButton();
        jButton2Cancelar = new javax.swing.JButton();
        jButton3Salvar = new javax.swing.JButton();
        jButton4Atualizar = new javax.swing.JButton();
        jButton5Excluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Cliente"));

        jLabel1.setText("Nome:");

        jLabel2.setText("Endereço:");

        jLabel3.setText("Email:");

        jLabel4.setText("Telefone:");

        jTextFieldnome.setEnabled(false);
        jTextFieldnome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextFieldnomeActionPerformed(evt);
            }
        });

        jTextFieldendereco.setEnabled(false);

        jTextFieldemail.setEnabled(false);

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(jLabel4))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(15, 15, 15)
                                .addComponent(jTextFieldemail))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(18, 18, 18)
                                .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 57, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldnome)
                            .addComponent(jTextFieldendereco))))
                .addGap(10, 10, 10))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(14, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(153, 153, 153)));

        jButton1Inserir.setText("Inserir");
        jButton1Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1InserirActionPerformed(evt);
            }
        });

        jButton2Cancelar.setText("Cancelar");
        jButton2Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelarActionPerformed(evt);
            }
        });

        jButton3Salvar.setText("Salvar");
        jButton3Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SalvarActionPerformed(evt);
            }
        });

        jButton4Atualizar.setText("Atualizar");
        jButton4Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4AtualizarActionPerformed(evt);
            }
        });

        jButton5Excluir.setText("Excluir");
        jButton5Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1Inserir)
                .addGap(18, 18, 18)
                .addComponent(jButton2Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jButton3Salvar)
                .addGap(31, 31, 31)
                .addComponent(jButton4Atualizar)
                .addGap(28, 28, 28)
                .addComponent(jButton5Excluir)
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(25, 25, 25)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Inserir)
                    .addComponent(jButton2Cancelar)
                    .addComponent(jButton3Salvar)
                    .addComponent(jButton4Atualizar)
                    .addComponent(jButton5Excluir))
                .addContainerGap(32, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de Clientes"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 139, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jTextFieldnomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextFieldnomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextFieldnomeActionPerformed

    private void jButton3SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SalvarActionPerformed
        // TODO add your handling code here:
         if(jTextFieldnome.isEnabled()){
           Cliente usu = new Cliente();
            
            if(jTextFieldnome.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o nome do cliente!");
                return;
            }
            else{
                usu.setNome(jTextFieldnome.getText());
            }
            if(jTextFieldendereco.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o endereço do cliente!");
                return;
            }
            else{
                usu.setEndereço(jTextFieldendereco.getText());
            }
             if(jTextFieldemail.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o email do cliente!");
                return;
            }
            else{
                usu.setEmail(jTextFieldemail.getText());
            }
             if(jFormattedTextFieldTelefone.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o telefone do cliente!");
                return;
            }
            else{
                usu.setTelefone(jFormattedTextFieldTelefone.getText());
            }
             
             clienteDAO.cadastrar(usu);
             carregaCliente();
             jButton2CancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton3SalvarActionPerformed

    private void jButton5ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ExcluirActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Slelecione uma linha da tabela!");
            
        }
        else if(JOptionPane.showConfirmDialog(this,"Tem certeza que deseja excluir este cliente?")==JOptionPane.YES_OPTION){
            id=(int)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            clienteDAO.excluir(id);
             carregaCliente();
             jButton2CancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton5ExcluirActionPerformed

    private void jButton1InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1InserirActionPerformed
        // TODO add your handling code here:
        jTextFieldnome.setEnabled(true);
        jTextFieldendereco.setEnabled(true);
        jTextFieldemail.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
    }//GEN-LAST:event_jButton1InserirActionPerformed

    private void jButton2CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelarActionPerformed
        // TODO add your handling code here:
         jTextFieldnome.setText("");
        jTextFieldendereco.setText("");
        jTextFieldemail.setText("");
        jFormattedTextFieldTelefone.setText("");
        
         jTextFieldnome.setEnabled(false);
        jTextFieldendereco.setEnabled(false);
        jTextFieldemail.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
    }//GEN-LAST:event_jButton2CancelarActionPerformed

    private void jButton4AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4AtualizarActionPerformed
        // TODO add your handling code here:
        if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela!");
        }
        else if(JOptionPane.showConfirmDialog(this,"Tem certeza que deseja alterar o cliente "+ jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1)+"!")
                ==JOptionPane.OK_OPTION){
            Cliente usu = new Cliente();
            
            usu.setId(id);
            if(jTextFieldnome.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o nome do cliente!");
                return;
            
        }else{
            usu.setNome(jTextFieldnome.getText());
        }
            if(jTextFieldendereco.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o endereço do cliente!");
                return;
            }
            else{
                usu.setEndereço(jTextFieldendereco.getText());
            }
             if(jTextFieldemail.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o produto do cliente!");
                return;
            }
            else{
                usu.setEmail(jTextFieldemail.getText());
            }
             if(jFormattedTextFieldTelefone.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o telefone do cliente!");
                return;
            }
            else{
                usu.setTelefone(jFormattedTextFieldTelefone.getText());
            }
             
             clienteDAO.alterar(usu);
             carregaCliente();
             jButton2CancelarActionPerformed(evt);
        }
        
    }//GEN-LAST:event_jButton4AtualizarActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         jButton1InserirActionPerformed(null);
       id= (int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0);
          jTextFieldnome.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1));
          jTextFieldendereco.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2));
          jTextFieldemail.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3));
          jFormattedTextFieldTelefone.setText(""+jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameCliente.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameCliente().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Inserir;
    private javax.swing.JButton jButton2Cancelar;
    private javax.swing.JButton jButton3Salvar;
    private javax.swing.JButton jButton4Atualizar;
    private javax.swing.JButton jButton5Excluir;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldemail;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldnome;
    // End of variables declaration//GEN-END:variables
public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);

}
    private void carregaCliente() {
        
    try{
        jTable1.setModel(buildTableModel(clienteDAO.consulta()));
    }   catch (SQLException ex) {
            Logger.getLogger(NewJFrameCliente.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
