/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Interfaces;



import DAO.funcionariosDAO;
import Entidades.Funcionarios;
import java.awt.event.ActionEvent;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.util.Vector;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Miriam
 */
public class NewJFrameFuncionarios extends javax.swing.JFrame {
    private int id;

    /**
     * Creates new form NewJFrameFuncionarios
     */
    public NewJFrameFuncionarios() {
        initComponents();
        carregaFuncionarios();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jTextFieldcargo = new javax.swing.JTextField();
        jTextFieldnome = new javax.swing.JTextField();
        jTextFieldendereco = new javax.swing.JTextField();
        jTextFieldsalario = new javax.swing.JTextField();
        jFormattedTextFieldTelefone = new javax.swing.JFormattedTextField();
        jPanel2 = new javax.swing.JPanel();
        jButton1Inserir = new javax.swing.JButton();
        jButton2Cancelar = new javax.swing.JButton();
        jButton3Salvar = new javax.swing.JButton();
        jButton4Atualizar = new javax.swing.JButton();
        jButton5Excluir = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Adicionar Funcionarios"));
        jPanel1.setEnabled(false);

        jLabel1.setText("Cargo:");

        jLabel2.setText("Nome:");

        jLabel3.setText("Endereço:");

        jLabel4.setText("Telefone:");

        jLabel5.setText("Salario:");

        jTextFieldcargo.setEnabled(false);

        jTextFieldnome.setEnabled(false);

        jTextFieldendereco.setEnabled(false);

        jTextFieldsalario.setEnabled(false);

        try {
            jFormattedTextFieldTelefone.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(###)####-#####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jFormattedTextFieldTelefone.setEnabled(false);
        jFormattedTextFieldTelefone.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jFormattedTextFieldTelefoneActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel5)
                    .addComponent(jLabel4)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldendereco)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jTextFieldsalario, javax.swing.GroupLayout.PREFERRED_SIZE, 66, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addGap(10, 10, 10))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jTextFieldnome)
                        .addContainerGap())
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jTextFieldcargo, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jTextFieldnome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextFieldcargo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(jTextFieldendereco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(jFormattedTextFieldTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jTextFieldsalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jButton1Inserir.setText("Inserir");
        jButton1Inserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1InserirActionPerformed(evt);
            }
        });

        jButton2Cancelar.setText("Cancelar");
        jButton2Cancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2CancelarActionPerformed(evt);
            }
        });

        jButton3Salvar.setText("Salvar");
        jButton3Salvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3SalvarActionPerformed(evt);
            }
        });

        jButton4Atualizar.setText("Atualizar");
        jButton4Atualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4AtualizarActionPerformed(evt);
            }
        });

        jButton5Excluir.setText("Excluir");
        jButton5Excluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ExcluirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jButton1Inserir)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton2Cancelar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jButton3Salvar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton4Atualizar)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jButton5Excluir)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1Inserir)
                    .addComponent(jButton2Cancelar)
                    .addComponent(jButton3Salvar)
                    .addComponent(jButton4Atualizar)
                    .addComponent(jButton5Excluir))
                .addContainerGap(28, Short.MAX_VALUE))
        );

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Lista de funcionarios"));

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 59, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1InserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1InserirActionPerformed
        // TODO add your handling code here:
         jTextFieldcargo.setEnabled(true);
        jTextFieldnome.setEnabled(true);
        jTextFieldendereco.setEnabled(true);
        jFormattedTextFieldTelefone.setEnabled(true);
        jTextFieldsalario.setEnabled(true);
    }//GEN-LAST:event_jButton1InserirActionPerformed

    private void jButton2CancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2CancelarActionPerformed
        // TODO add your handling code here:
         jTextFieldcargo.setText("");
        jTextFieldnome.setText("");
        jTextFieldendereco.setText("");
        jFormattedTextFieldTelefone.setText("");
        jTextFieldsalario.setText("");
        
         jTextFieldcargo.setEnabled(false);
        jTextFieldnome.setEnabled(false);
        jTextFieldendereco.setEnabled(false);
        jFormattedTextFieldTelefone.setEnabled(false);
        jTextFieldsalario.setEnabled(false);
    }//GEN-LAST:event_jButton2CancelarActionPerformed

    private void jButton3SalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3SalvarActionPerformed
        // TODO add your handling code here:
        if(jTextFieldcargo.isEnabled()){
           Funcionarios usu = new Funcionarios();
            
            if(jTextFieldcargo.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o cargo do funcionario!");
                return;
            }
            else{
                usu.setCargo(jTextFieldcargo.getText());
            }
            if(jTextFieldnome.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o nome do funcionario!");
                return;
            }
            else{
                usu.setNome(jTextFieldnome.getText());
            }
             if(jTextFieldendereco.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o endereço do funcionario!");
                return;
            }
            else{
                usu.setEndereco(jTextFieldendereco.getText());
            }
             if(jFormattedTextFieldTelefone.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o telefone do funcionario!");
                return;
            }
            else{
                usu.setTelefone( jFormattedTextFieldTelefone.getText());
            }
             if(jTextFieldsalario.getText().equals("")){
                 JOptionPane.showMessageDialog(this,"Insira o salario do funcionario!");
                 return;
             }
             else{
                 usu.setSalario(jTextFieldsalario.getText());
             }
             
             funcionariosDAO.cadastrar(usu);
             carregaFuncionarios();
             jButton2CancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton3SalvarActionPerformed

    private void jButton4AtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4AtualizarActionPerformed
        // TODO add your handling code here: 
             if(jTable1.getSelectedRow()==-1){
            JOptionPane.showMessageDialog(this,"Selecione uma linha da tabela!");
        }
        else if(JOptionPane.showConfirmDialog(this,"Tem certeza que deseja alterar o funcionario "+ jTable1.getModel().getValueAt(jTable1.getSelectedRow(),1)+"!")
                ==JOptionPane.OK_OPTION){
            Funcionarios usu = new Funcionarios();
            
            usu.setId(id);
            if(jTextFieldcargo.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o cargo do funcionario!");
                return;
            }
            else{
                usu.setCargo(jTextFieldcargo.getText());
            }
            if(jTextFieldnome.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o nome do funcionario!");
                return;
            }
            else{
                usu.setNome(jTextFieldnome.getText());
            }
             if(jTextFieldendereco.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o endereço do funcionario!");
                return;
            }
            else{
                usu.setEndereco(jTextFieldendereco.getText());
            }
             if( jFormattedTextFieldTelefone.getText().equals("")){
                JOptionPane.showMessageDialog(this,"Insira o telefone do funcionario!");
                return;
            }
            else{
                usu.setTelefone( jFormattedTextFieldTelefone.getText());
            }
             if(jTextFieldsalario.getText().equals("")){
                 JOptionPane.showMessageDialog(this,"Insira o salario do funcionario!");
                 return;
             }
             else{
                 usu.setSalario(jTextFieldsalario.getText());
             }
             
             funcionariosDAO.alterar(usu);
             carregaFuncionarios();
            jButton2CancelarActionPerformed(evt);
        
        }
    }//GEN-LAST:event_jButton4AtualizarActionPerformed

    private void jButton5ExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ExcluirActionPerformed
        // TODO add your handling code here:
         if(jTable1.getSelectedRow() == -1){
            JOptionPane.showMessageDialog(this,"Slelecione uma linha da tabela!");
            
        }
        else if(JOptionPane.showConfirmDialog(this,"Tem certeza que deseja excluir este funcionario?")==JOptionPane.YES_OPTION){
            id=(int)jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 0);
            funcionariosDAO.excluir(id);
             carregaFuncionarios();
            jButton2CancelarActionPerformed(evt);
        }
    }//GEN-LAST:event_jButton5ExcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        // TODO add your handling code here:
         jButton1InserirActionPerformed(null);
       id= (int) jTable1.getModel().getValueAt(jTable1.getSelectedRow(),0);
        jTextFieldnome.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 1));
          jTextFieldendereco.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 2));
          jTextFieldcargo.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 3));
           jFormattedTextFieldTelefone.setText(""+jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 4));
          jTextFieldsalario.setText("" +jTable1.getModel().getValueAt(jTable1.getSelectedRow(), 5));
    }//GEN-LAST:event_jTable1MouseClicked

    private void jFormattedTextFieldTelefoneActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jFormattedTextFieldTelefoneActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jFormattedTextFieldTelefoneActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrameFuncionarios.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrameFuncionarios().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1Inserir;
    private javax.swing.JButton jButton2Cancelar;
    private javax.swing.JButton jButton3Salvar;
    private javax.swing.JButton jButton4Atualizar;
    private javax.swing.JButton jButton5Excluir;
    private javax.swing.JFormattedTextField jFormattedTextFieldTelefone;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextFieldcargo;
    private javax.swing.JTextField jTextFieldendereco;
    private javax.swing.JTextField jTextFieldnome;
    private javax.swing.JTextField jTextFieldsalario;
    // End of variables declaration//GEN-END:variables

public static DefaultTableModel buildTableModel(ResultSet rs)
        throws SQLException {

    ResultSetMetaData metaData = rs.getMetaData();

    // names of columns
    Vector<String> columnNames = new Vector<String>();
    int columnCount = metaData.getColumnCount();
    for (int column = 1; column <= columnCount; column++) {
        columnNames.add(metaData.getColumnName(column));
    }

    // data of the table
    Vector<Vector<Object>> data = new Vector<Vector<Object>>();
    while (rs.next()) {
        Vector<Object> vector = new Vector<Object>();
        for (int columnIndex = 1; columnIndex <= columnCount; columnIndex++) {
            vector.add(rs.getObject(columnIndex));
        }
        data.add(vector);
    }

    return new DefaultTableModel(data, columnNames);
}
  private void carregaFuncionarios() {
        
    try{
        jTable1.setModel(buildTableModel(funcionariosDAO.consulta()));
    }   catch (SQLException ex) {
            Logger.getLogger(NewJFrameFuncionarios.class.getName()).log(Level.SEVERE, null, ex);
        }
    }
}
